---
title: "OME2 Documentation"
description: "Documentation for OpenMapsForEurope OME2"
baseurl: ""
url: "https://openmapsforeurope2.github.io"
theme: minima
plugins:
  - jekyll-feed
markdown_ext: "md"
---
